RentCar/Models/Cars.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RentCar.Models
{
    public class Cars
    {
        public int id { get; set; }


        [Display(Name = "category")]
        public string category { get; set; }

        [Required]
        [Display(Name = "Model")]
        public string Model { get; set; }


        [Display(Name = "Color")]
        public string Color { get; set; }


        [Display(Name = "Image")]
        public string Image { get; set; }

        [Required]
        [Display(Name = "NumberOfChairs")]
        public int NumberOfChairs { get; set; }


        [Display(Name = "State")]
        public string State { get; set; }

        [Required]
        [Display(Name = "Amount")]
        public string Amount { get; set; }

    }
}

RentCar/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentCar.Models;
using WebApplication1.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Web.Helpers;
using System.Configuration;

using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.AspNet.Mvc;
using Twilio.Types;

namespace RentCar.Controllers
{
    public class CarsController : TwilioController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public object upload { get; private set; }

        // GET: Cars
        public ActionResult Index()
        {
            return View(db.Cars.ToList());
        }

        // GET: Cars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new System.Web.Mvc.HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cars cars = db.Cars.Find(id);
            if (cars == null)
            {
                return HttpNotFound();
            }
            return View(cars);
        }

        // GET: Cars/Create
        public ActionResult Create()
        {
            ViewBag.category = new SelectList(new[] { "BMW", "Mercides Benz", "Audi", "Chevrolet", "Pejout", "Renault", "Hyundai", "Honda", "Toyota", "Range Rover", "KIA", "Nissan", "Mazda", "Jeep", "FIAT", "Sozuki", "Spranza", "Other" });
            ViewBag.Color = new SelectList(new[] { "White", "Black", "Gray", "Selver", "Red", "Blue", "Brouwn", "Green", "Others" });
            ViewBag.State = new SelectList(new[] { "Available", "UnAvailable" });
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cars cars, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                ViewBag.category = new SelectList(new[] { "BMW", "Mercides Benz", "Audi", "Chevrolet", "Pejout", "Renault", "Hyundai", "Honda", "Toyota", "Range Rover", "KIA", "Nissan", "Mazda", "Jeep", "FIAT", "Sozuki", "Spranza", "Other" });
                ViewBag.Color = new SelectList(new[] { "White", "Black", "Gray", "Selver", "Red", "Blue", "Brouwn", "Green", "Others" });
                ViewBag.State = new SelectList(new[] { "Available", "UnAvailable" });
                string path = Path.Combine(Server.MapPath("~/uploads"), upload.FileName);
                upload.SaveAs(path);
                cars.Image = upload.FileName;
                db.Cars.Add(cars);
                db.SaveChanges();
            
                  foreach(var item in db.Users)
                  
                    if (item.CarType == cars.category)
                    {

                        WebMail.SmtpServer = "smtp.gmail.com";

                        WebMail.SmtpPort = 587;
                        WebMail.SmtpUseDefaultCredentials = true;

                        WebMail.EnableSsl = true;

                        WebMail.UserName = "muhammad.wahed30@gmail.com";
                        WebMail.Password = "01150235008";


                        WebMail.From = "muhammad.wahed30@gmail.com";
                        string ClientEmail = item.Email;
                        string Subject = "New Car";
                        string body = "There is a new car of category ";
                        body += item.CarType + " has been added to Go Car Website you can show it by visit the website ";
                        WebMail.Send(to: ClientEmail, subject: Subject, body: body, isBodyHtml: true);
                    }

              



                return RedirectToAction("Index");
            }

            return View(cars);
        }

        // GET: Cars/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.category = new SelectList(new[] { "BMW", "Mercides Benz", "Audi", "Chevrolet", "Pejout", "Renault", "Hyundai", "Honda", "Toyota", "Range Rover", "KIA", "Nissan", "Mazda", "Jeep", "FIAT", "Sozuki", "Spranza", "Other" });
            ViewBag.Color = new SelectList(new[] { "White", "Black", "Gray", "Selver", "Red", "Blue", "Brouwn", "Green", "Others" });
            ViewBag.State = new SelectList(new[] { "Available", "UnAvailable" });

            if (id == null)
            {
                return new System.Web.Mvc.HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cars cars = db.Cars.Find(id);
            if (cars == null)
            {
                return HttpNotFound();
            }
                return View(cars);

        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cars cars, HttpPostedFileBase upload)
        {

            if (ModelState.IsValid)
            {
                ViewBag.category = new SelectList(new[] { "BMW", "Mercides Benz", "Audi", "Chevrolet", "Pejout", "Renault", "Hyundai", "Honda", "Toyota", "Range Rover", "KIA", "Nissan", "Mazda", "Jeep", "FIAT", "Sozuki", "Spranza", "Other" });
                ViewBag.Color = new SelectList(new[] { "White", "Black", "Gray", "Selver", "Red", "Blue", "Brouwn", "Green", "Others" });
                ViewBag.State = new SelectList(new[] { "Available", "UnAvailable" });
                if(upload!=null)
                {
                    string path = Path.Combine(Server.MapPath("~/uploads"), upload.FileName);
                    upload.SaveAs(path);
                    cars.Image = upload.FileName;
                }

              
               
                db.Entry(cars).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cars);
        }

        public ActionResult Search()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Search(string SearchId)
        {

            var result = db.Cars.Where(c => c.id.ToString().Contains(SearchId)).ToList();

            return View(result);

        }

        // GET: Cars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new System.Web.Mvc.HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cars cars = db.Cars.Find(id);
            if (cars == null)
            {
                return HttpNotFound();
            }
            return View(cars);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cars cars = db.Cars.Find(id);
            db.Cars.Remove(cars);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public JsonResult RentCash(string from,string to,string carId)
        {
            try
            {
                int CarId = int.Parse(carId);
                Cars car = db.Cars.Find(CarId);
                int RentByDay = int.Parse(car.Amount);
                TimeSpan difference = Convert.ToDateTime(to) - Convert.ToDateTime(from);
                int Days = Convert.ToInt32(difference.TotalDays);
                int RentAmount = RentByDay * Days;
                string UserId = User.Identity.GetUserId();
                var user = db.Users.Where(u => u.Id ==UserId ).FirstOrDefault() ;
                if (RentAmount <= user.Balance)
                {
                    Rent rent = new Rent();
                    rent.CarId = car.id;
                    rent.From = Convert.ToDateTime(from);
                    rent.To = Convert.ToDateTime(to);
                    rent.UserId = User.Identity.GetUserId();
                    rent.TotalAmount = RentAmount;
                    user.Balance = user.Balance - RentAmount;
                    car.State = "UnAvailable";
                    db.Entry(user).State = EntityState.Modified;
                    db.Entry(car).State = EntityState.Modified;
                    db.Rents.Add(rent);
                    db.SaveChanges();

                    WebMail.SmtpServer = "smtp.gmail.com";

                    WebMail.SmtpPort = 587;
                    WebMail.SmtpUseDefaultCredentials = true;

                    WebMail.EnableSsl = true;

                    WebMail.UserName = "muhammad.wahed30@gmail.com";
                    WebMail.Password = "01150235008";


                    WebMail.From = "muhammad.wahed30@gmail.com";
                    string AdminEmail = "muhammedwahed19@yahoo.com";
                    string Subject = "New Rent";
                    string body = "User: ";
                    body += User.Identity.Name + " has rent the car: ";
                    body += car.Model + "with Car ID: ";
                    body += car.id + "for: ";
                    body += Days.ToString() + " days";
                    WebMail.Send(to: AdminEmail, subject: Subject, body: body, isBodyHtml: true);
                    ViewBag.Status = "Email Sent Successfully.";
                    int rid = rent.Id;

                    var accountSid = "AC8608432847456494ff979ddc7568e534";
                    var authToken = "88b42744c68db78ef3b56da4a266a08a";
                    TwilioClient.Init(accountSid, authToken);

RentCar/Views/Cars/Create.cshtml
@model RentCar.Models.Cars

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/shared/_AdminLayout.cshtml";
}

<div class="container">
    <h1 class="text-center add_car_heading">ADD CAR</h1>

    @using (Html.BeginForm("Create", "Cars", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="alert alert-danger" id="error-div" style="display:none">
                <h4>Create</h4>
            </div>

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.DropDownList("category", null, new { @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.Model, new { placeholder = "Model", @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.DropDownList("Color", null, new { @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="file" name="upload" required />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.NumberOfChairs, new { placeholder = "Number Of Chairs", @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.NumberOfChairs, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.DropDownList("State", null, new { @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.Amount, new { placeholder = "Amount", @class = "form-control money" })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Add Car" class="btn btn-primary btn-lg covbtn" />
                </div>
            </div>
        </div>

        <div class="text-center" style="color:#2E86C1; font-size:28px;">
            @Html.ActionLink("Back to cars List", "Index")
        </div>

    }

</div>

RentCar/Views/Cars/Delete.cshtml
@model RentCar.Models.Cars

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/shared/_AdminLayout.cshtml";
}
<div class="container">
    <h1 class="text-center" style="color:#2E86C1; font-weight:bold;">Delete</h1>

    <h3 class="text-center">Are you sure you want to delete this ?</h3>
    <div>

        <div class="car_box">
            <div class="row">

                <div class="col-md-4">
                    <img src="~/uploads/@Html.DisplayFor(model=>model.Image)"
                         class="thumbnail"
                         style="width:250px; height:220px;" />
                </div>

                <div class="col-md-4">
                    <ul>
                        <li><p class="cdetails">Car Category:<span class="car_details"> @Html.DisplayFor(model => model.category)</span></p></li>
                        <li><p class="cdetails">Color:<span class="car_details">@Html.DisplayFor(model => model.Color)</span></p></li>
                        <li><p class="cdetails">Price:<span class="car_details">@Html.DisplayFor(model => model.Amount)</span></p></li>
                        <li><p class="cdetails">Number of chairs:<span class="car_details">@Html.DisplayFor(model => model.NumberOfChairs)</span></p></li>
                        <li><p class="cdetails">Model:<span class="car_details">@Html.DisplayFor(model => model.Model)</span></p></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-danger btn-lg" />

                        </div>
                    }
                </div>


            </div>
        </div>

        <div class="text-center" style="margin-top:20px; font-size:28px; text-decoration:none;"> @Html.ActionLink("Back to List", "Index") </div>


    </div>
</div>

RentCar/Views/Cars/Details.cshtml
@model RentCar.Models.Cars
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/shared/_MainLayout.cshtml";
    var db = new RentCar.Models.Rent();
}

<h1 class="CarD_h text-center">Car Details</h1>
<div>
    <section class="CarDetails">
        <div class="row">
            <div class="col-md-4">
                <img src="~/uploads/@Html.DisplayFor(model => model.Image)"
                     class="thumbnail"
                     style="width:250px; height:250px;" />
            </div>
            <div class="col-md-4">
                <ul>
                    <li><p class="cdetails">Car Category :  <span class="car_detail"> @Html.DisplayFor(model => model.category)</span></p></li>
                    <li><p class="cdetails">Model :  <span class="car_detail">@Html.DisplayFor(model => model.Model)</span></p></li>
                    <li><p class="cdetails">Color :  <span class="car_detail">@Html.DisplayFor(model => model.Color)</span></p></li>
                    <li><p class="cdetails">State :  <span class="car_detail">@Html.DisplayFor(model => model.State)</span></p></li>
                    <li><p class="cdetails">Number of chairs :  <span class="car_detail">@Html.DisplayFor(model => model.NumberOfChairs)</span></p></li>
                    <li><p class="cdetails">Price :  <span class="car_detail">@Html.DisplayFor(model => model.Amount)</span>    $Per Day</p></li>
                </ul>
                <hr />
                <p>
                    <input type="text" id="CarId" value="@Model.id" style="display:none" />
                    @if (Model.State.Equals("Available"))
                    {
                        <button id="btnRent" class="btn btn-primary btn-block btn-lg rntbtn" data-toggle="modal" data-target="#rentModal">Rent</button>
                    }


                </p>
            </div>
        </div>
    </section>
</div>

RentCar/Views/Cars/Edit.cshtml
@model RentCar.Models.Cars

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/shared/_AdminLayout.cshtml";
    
 }
<div class="container">
    <div class="text-center" style="font-size:32px; color:#2E86C1; font-weight:bold;">
        <p>Update Car</p>
    </div>

    @using (Html.BeginForm("Edit", "Cars", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="alert alert-danger" id="error-div" style="display:none">
                <h4>Create</h4>
            </div>

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.DropDownList("category", null, new { @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.Model, new { placeholder = "Model", @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.DropDownList("Color", null, new { @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

           
            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.NumberOfChairs, new { placeholder = "Number Of Chairs", @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.NumberOfChairs, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.DropDownList("State", null, new { @class = "form-control sel1" })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.Amount, new { placeholder = "Amount", @class = "form-control money" })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">
                        <img src="~/uploads/@Model.Image" class="EditImg" width="200" height="200" />
                        <input type="file" name="upload" value="@Model.Image" />
                        @Html.TextBoxFor(model => model.Image, new { placeholder = "Model", @class = "form-control sel1", style = "display:none;" })
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Update" class="btn btn-primary btn-lg covbtn" />
                </div>
            </div>
        </div>

     
    }

</div>

RentCar/Views/Cars/Index.cshtml
@model IEnumerable<RentCar.Models.Cars>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_AdminLayout.cshtml";
}

<h1 class="text-center add_car_heading">CARS</h1>


<div class="text-center" style="font-size:28px; text-decoration:none; font-weight:bold">
    @Html.ActionLink("Add New Car", "Create")
</div>
<br />


@using (Html.BeginForm("Search", "Cars", FormMethod.Post))
{
  <input type="text" name="SearchId"
       id="SearchId"
       class="form-control"
       placeholder="Search Car ID"
       style="width:300px; margin:auto;" />
  }

    @foreach (var item in Model)
    {

        <div class="container">

            <div class="car_box">
                <div class="row">

                    <div class="col-md-4">
                        <img src="~/uploads/@Html.DisplayFor(model => item.Image)"
                             class="thumbnail"
                             style="width:250px; height:220px;" />
                    </div>

                    <div class="col-md-4">
                        <ul>
                            <li><p class="cdetails">Car ID:<span class="car_details"> @Html.DisplayFor(modelItem => item.id)</span></p></li>

                            <li><p class="cdetails">Car Category:<span class="car_details"> @Html.DisplayFor(modelItem => item.category)</span></p></li>
                            <li><p class="cdetails">Color:<span class="car_details">@Html.DisplayFor(modelItem => item.Color)</span></p></li>
                            <li><p class="cdetails">Price:<span class="car_details">@Html.DisplayFor(modelItem => item.Amount)</span></p></li>
                            <li><p class="cdetails">Number of chairs:<span class="car_details">@Html.DisplayFor(modelItem => item.NumberOfChairs)</span></p></li>
                            <li><p class="cdetails">State:<span class="car_details"> @Html.DisplayFor(modelItem => item.State)</span></p></li>
                            <li><p class="cdetails">Model:<span class="car_details"> @Html.DisplayFor(modelItem => item.Model)</span></p></li>
                        </ul>
                    </div>

                    <div class="col-md-2">

                        @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btn btn-danger delete_btn btn-lg" })
                        <br />
                        @Html.ActionLink("Update", "Edit", new { id = item.id }, new { @class = "btn btn-primary update_btn btn-lg" })

                    </div>
                </div>
            </div>
        </div>

    }

        

RentCar/Views/Cars/Report.cshtml
@model IEnumerable<RentCar.Models.Cars>

@{

    ViewBag.Title = "Report";
    Layout = "~/Views/shared/_AdminLayout.cshtml";
    float ava = 0;
    float unava = 0;
    float count = 0;
    float ava_perc, unava_perc;
    foreach (var item1 in Model)
    {
        if (item1.State.Equals("Available"))
        {
            ava++;
        }
        else
        {
            unava++;
        }
        count++;
    }
    ava_perc = (ava * 100) / count;
    unava_perc = (unava * 100) / count;
}

<h1 class="report_heading">Cars Report</h1>

<div class="container">

<div class="progress">
    <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="@ava_perc" aria-valuemin="0" aria-valuemax="100" style="width: @ava_perc%; font-size:18px;">
        @ava_perc % Available
    </div>
</div>
<div class="progress">
    <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar" aria-valuenow="@unava_perc" aria-valuemin="0" aria-valuemax="100" style="width: @unava_perc%; font-size:18px;">
        @unava_perc % Unavailable
    </div>
</div>

    <div class="row">
        
        <div class="col-md-5 col-xs-12 avadiv">
            
                    <h1 class="available_heading">Available</h1>
                
            @foreach (var item in Model)
            {
                if (item.State.Equals("Available"))
                {
                    <h2 style="text-align:center">Car @item.id</h2>
                    <ul style="font-size:16px;">
                        <li>
                            Category: @item.category
                        </li>
                        <li>
                            Model: @item.Model
                        </li>
                        <li>
                            Color: @item.Color
                        </li>
                        <li>
                            Number of seats: @item.NumberOfChairs
                        </li>
                        <li>
                            Price: @item.Amount $/Day
                        </li>
                    </ul>
                    <hr />
                }
            }
        </div>
        <div class="col-md-2 col-xs-12">

        </div>
            
            <div class="col-md-5 col-xs-12 unavadiv">
                <h1 class="unavailable_heading">Unavailable</h1>

                @foreach (var item2 in Model)
                {
                    if (item2.State.Equals("UnAvailable"))
                    {
                        <h2 style="text-align:center">Car @item2.id</h2>
                        <ul style="font-size:16px;">
                            <li>
                                Category: @item2.category
                            </li>
                            <li>
                                Model: @item2.Model
                            </li>
                            <li>
                                Color: @item2.Color
                            </li>
                            <li>
                                Number of seats: @item2.NumberOfChairs
                            </li>
                            <li>
                                Price: @item2.Amount $/Day
                            </li>
                        </ul>
                        <hr />
                    }
                }
            </div>
        </div>
</div>

RentCar/Views/Cars/Search.cshtml
@model IEnumerable<RentCar.Models.Cars>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/shared/_AdminLayout.cshtml";
}

<h1 class="text-center add_car_heading">CARS</h1>


<div class="text-center" style="font-size:28px; text-decoration:none; font-weight:bold">
    @Html.ActionLink("Add New Car", "Create")
</div>
<br />

@using (Html.BeginForm("Search", "Cars", FormMethod.Post))
    {
<input type="text" name="SearchId"
       id="SearchId"
       class="form-control"
       placeholder="Search Car ID"
       style="width:300px; margin:auto;" />
    }

    @foreach (var item in Model)
    {

        <div class="container">

            <div class="car_box">
                <div class="row">

                    <div class="col-md-4">
                        <img src="~/uploads/@Html.DisplayFor(model => item.Image)"
                             class="thumbnail"
                             style="width:250px; height:220px;" />
                    </div>

                    <div class="col-md-4">
                        <ul>
                            <li><p class="cdetails">Car ID:<span class="car_details"> @Html.DisplayFor(modelItem => item.id)</span></p></li>

                            <li><p class="cdetails">Car Category:<span class="car_details"> @Html.DisplayFor(modelItem => item.category)</span></p></li>
                            <li><p class="cdetails">Color:<span class="car_details">@Html.DisplayFor(modelItem => item.Color)</span></p></li>
                            <li><p class="cdetails">Price:<span class="car_details">@Html.DisplayFor(modelItem => item.Amount)</span></p></li>
                            <li><p class="cdetails">Number of chairs:<span class="car_details">@Html.DisplayFor(modelItem => item.NumberOfChairs)</span></p></li>
                            <li><p class="cdetails">State:<span class="car_details"> @Html.DisplayFor(modelItem => item.State)</span></p></li>
                            <li><p class="cdetails">Model:<span class="car_details"> @Html.DisplayFor(modelItem => item.Model)</span></p></li>
                        </ul>
                    </div>

                    <div class="col-md-2">

                        @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btn btn-danger delete_btn btn-lg" })
                        <br />
                        @Html.ActionLink("Update", "Edit", new { id = item.id }, new { @class = "btn btn-primary update_btn btn-lg" })

                    </div>
                </div>
            </div>
        </div>
        }